name: CI/CD Flask App to Kubernetes

on:
  push:
    branches: [main] # Trigger on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: haiminh287/flask-app:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t $DOCKER_IMAGE ./app
          docker push $DOCKER_IMAGE

      - name: Deploy to Kubernetes via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.MASTER_HOST }}
          username: ubuntu
          key: ${{ secrets.MASTER_SSH_KEY }}
          script: |
            docker pull $DOCKER_IMAGE
            kubectl delete -f ~/k8s || true
            kubectl apply -f ~/k8s
          envs: DOCKER_IMAGE
